# Generated by Django 5.2.3 on 2025-08-18 11:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
